=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0x0a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0x10"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0x10" elementFormDefault="qualified">
	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>
	<xs:element name="Type_0x0a">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				5.3.9 应用自定义策略
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="AppType" type="u:UINT1" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="AppID" type="u:UINT2" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="AppName" type="string" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="U_Signatures">
							<xs:annotation>
								<xs:documentation xml:lang="zh">
									自定义应用特征组，U_Signatures的子元素个数对应U_SignatureNum 字段，1 Bytes
								</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="U_Signature" maxOccurs="unbounded"
										minOccurs="1">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="U_Protocol" type="u:UINT1"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="U_SourceIP" type="u:IPType"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="U_SourcePort" type="u:UINT2"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="U_DestIP" type="u:IPType"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="U_DestPort" type="u:UINT2"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="U_KWs">
													<xs:annotation>
														<xs:documentation xml:lang="zh">
															自定义应用的关键字，U_KWs的子元素个数对应U_KW_Num 字段，1 Bytes
														</xs:documentation>
													</xs:annotation>
													<xs:complexType>
														<xs:sequence>
															<xs:element name="U_KW" maxOccurs="unbounded"
																minOccurs="0">
																<xs:complexType>
																	<xs:sequence>
																		<xs:element name="U_OffsetBase" type="u:UINT1"
																			maxOccurs="1" minOccurs="1"></xs:element>
																		<xs:element name="U_Offset" type="u:UINT1"
																			maxOccurs="1" minOccurs="1"></xs:element>
																		<xs:element name="U_KWValue" type="string"
																			maxOccurs="1" minOccurs="1"></xs:element>
																	</xs:sequence>
																</xs:complexType>
															</xs:element>
														</xs:sequence>
													</xs:complexType>
												</xs:element>
												<xs:element name="MessageSerialNo" type="u:UINT4"
													maxOccurs="1" minOccurs="1" default="00000000"></xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/xml/msg_0x0a.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type_0x0a messageNo="0" messageSequenceNo="0"
	messageSerialNo="0" xmlns="http://www.example.org/msg_0x10" xmlns:u="http://www.example.org/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/msg_0x10 ../xsd/msg_0x0a.xsd ">
	<AppType>0</AppType>
	<AppID>0</AppID>
	<AppName>AppName</AppName>
	<U_Signatures>
		<U_Signature>
			<U_Protocol>0</U_Protocol>
			<U_SourceIP>IPv4</U_SourceIP>
			<U_SourcePort>0</U_SourcePort>
			<U_DestIP>IPv4</U_DestIP>
			<U_DestPort>0</U_DestPort>
			<U_KWs />
			<MessageSerialNo>00000000</MessageSerialNo>
		</U_Signature>
		<U_Signature>
			<U_Protocol>0</U_Protocol>
			<U_SourceIP>IPv4</U_SourceIP>
			<U_SourcePort>0</U_SourcePort>
			<U_DestIP>IPv4</U_DestIP>
			<U_DestPort>0</U_DestPort>
			<U_KWs></U_KWs>
			<MessageSerialNo>00000000</MessageSerialNo>
		</U_Signature>
	</U_Signatures>
</Type_0x0a>
