=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0x08.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0x08"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0x08" elementFormDefault="qualified">

	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>
	<xs:element name="Type_0x08">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				5.3.7 访问指定应用的用户统计策略
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="R_StartTime" type="u:UINT4"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="R_EndTime" type="u:UINT4" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="AppType" type="u:UINT1" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="AppID" type="u:UINT2" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="AppName" type="string" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="UserType" type="u:UINT1" maxOccurs="1"
							minOccurs="1">
						</xs:element>
						<xs:element name="MessageSerialNo" type="u:UINT4"
							maxOccurs="1" minOccurs="1"></xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/xml/msg_0x08.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type_0x08 messageNo="0" messageSequenceNo="0"
	messageSerialNo="0" xmlns="http://www.example.org/msg_0x08" xmlns:u="http://www.example.org/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/msg_0x08 ../xsd/msg_0x08.xsd ">
	<R_StartTime>0</R_StartTime>
	<R_EndTime>0</R_EndTime>
	<AppType>0</AppType>
	<AppID>0</AppID>
	<AppName>AppName</AppName>
	<UserType>0</UserType>
	<MessageSerialNo>0</MessageSerialNo>
</Type_0x08>
