=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0x85.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0x85"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0x85" elementFormDefault="qualified">
	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>

	<xs:element name="Type_0x85">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				用户/应用策略信息下发
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="Bind_Action" type="u:UINT1"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="UserType" type="u:UINT1" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="UserName" type="string" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="Messages">
							<xs:annotation>
								<xs:documentation xml:lang="zh">
									本用户待绑定的策略数，Messages的子元素个数对应MessageNum 字段，2 Bytes
								</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Message" maxOccurs="unbounded"
										minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="MessageType" type="u:UINT1"
													maxOccurs="1" minOccurs="1">
												</xs:element>
												<xs:element name="MessageNo" type="u:UINT2"
													maxOccurs="1" minOccurs="1">
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.tester/src/main/resources/xml/msg_0x85.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type_0x85 messageNo="0" messageSequenceNo="0"
	messageSerialNo="0" xmlns="http://www.ambimmort.com/msg_0x85" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ambimmort.com/msg_0x85 msg_0x85.xsd ">
	<Bind_Action>1</Bind_Action>
	<UserType>1</UserType>
	<UserName>abc</UserName>
	<Messages>
		<Message>
			<MessageType>1</MessageType>
			<MessageNo>1</MessageNo>
		</Message>
		<Message>
			<MessageType>1</MessageType>
			<MessageNo>1</MessageNo>
		</Message>
	</Messages>
</Type_0x85>

=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/xml/msg_0x85.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type_0x85 messageNo="0" messageSequenceNo="0"
	messageSerialNo="0" xmlns="http://www.example.org/msg_0x85" xmlns:u="http://www.example.org/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/msg_0x85 ../xsd/msg_0x85.xsd ">
	<Bind_Action>0</Bind_Action>
	<UserType>0</UserType>
	<UserName>tns:UserName</UserName>
	<Messages>
		<Message>
			<MessageType>0</MessageType>
			<MessageNo>0</MessageNo>
		</Message>
		<Message>
			<MessageType>0</MessageType>
			<MessageNo>0</MessageNo>
		</Message>
	</Messages>
</Type_0x85>
