=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0x09.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0x09"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0x09" elementFormDefault="qualified">
	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>

	<xs:element name="Type_0x09">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				5.3.8 流量镜像策略
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="MAppType" type="u:UINT1" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="MAppID" type="u:UINT2" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="MAppName" type="string" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="M_StartTime" type="u:UINT4"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="M_EndTime" type="u:UINT4" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="M_GroupNo" type="u:UINT1" maxOccurs="1"
							minOccurs="1">
						</xs:element>
						<xs:element name="M_Direction" type="u:UINT1"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="MessageSerialNo" type="u:UINT4"
							maxOccurs="1" minOccurs="1"></xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/xml/msg_0x09.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type_0x09 messageNo="0" messageSequenceNo="0"
	messageSerialNo="0" xmlns="http://www.example.org/msg_0x09" xmlns:u="http://www.example.org/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/msg_0x09 ../xsd/msg_0x09.xsd ">
	<MAppType>0</MAppType>
	<MAppID>0</MAppID>
	<MAppName>MAppName</MAppName>
	<M_StartTime>0</M_StartTime>
	<M_EndTime>0</M_EndTime>
	<M_GroupNo>0</M_GroupNo>
	<M_Direction>0</M_Direction>
	<MessageSerialNo>0</MessageSerialNo>
</Type_0x09>
