=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0x43.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0x43"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0x43" elementFormDefault="qualified">

	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>

	<xs:element name="Type_0x43">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				5.4.4 应用层 DDoS 异常流量管理策略
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="APP_Attack_Types" maxOccurs="1"
							minOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="zh">
									申请受保护的应用层攻击类型数，APP_Attack_Types子元素个数对应APP_Attack_Type_Num，1Bytes
								</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="APP_Attack" maxOccurs="unbounded"
										minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="APP_Attack_Type" type="u:UINT1"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="Attack_Threshold" type="u:UINT2"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="Attack_Control" type="u:UINT2"
													maxOccurs="1" minOccurs="1"></xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="MessageSerialNo" type="u:UINT4"
							maxOccurs="1" minOccurs="1" default="00000000"></xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/xml/msg_0x43.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type_0x43 messageNo="0" messageSequenceNo="0"
	messageSerialNo="0" xmlns="http://www.example.org/msg_0x43" xmlns:u="http://www.example.org/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/msg_0x43 ../xsd/msg_0x43.xsd ">
	<APP_Attack_Types>
		<APP_Attack>
			<APP_Attack_Type>0</APP_Attack_Type>
			<Attack_Threshold>0</Attack_Threshold>
			<Attack_Control>0</Attack_Control>
		</APP_Attack>
		<APP_Attack>
			<APP_Attack_Type>0</APP_Attack_Type>
			<Attack_Threshold>0</Attack_Threshold>
			<Attack_Control>0</Attack_Control>
		</APP_Attack>
	</APP_Attack_Types>
	<MessageSerialNo>00000000</MessageSerialNo>
</Type_0x43>
