=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0xcb.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0xcb"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0xcb" elementFormDefault="qualified">
	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>

	<xs:element name="Type_0xcb">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				信息推送触发网站列表定义
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="Trigger_HostListID" type="u:UINT1"></xs:element>
						<xs:element name="Trigger_Hosts" maxOccurs="1"
							minOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="zh">
									本列表所包含的网站数，Trigger_Hosts子元素个数对应Trigger_HostsNum字段，2 Bytes
								</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Trigger_Host" maxOccurs="unbounded"
										minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="HostName" type="string"
													maxOccurs="1" minOccurs="1"></xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.tester/src/main/resources/xml/msg_0xcb.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type_0xcb messageNo="0" messageSequenceNo="0"
	messageSerialNo="0" xmlns="http://www.example.org/msg_0xcb" xmlns:u="http://www.example.org/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/msg_0xcb ../xsd/msg_0xcb.xsd ">
	<Trigger_HostListID>0</Trigger_HostListID>
	<Trigger_Hosts>
		<Trigger_Host>
			<HostName>HostName</HostName>
		</Trigger_Host>
		<Trigger_Host>
			<HostName>HostName</HostName>
		</Trigger_Host>
		<Trigger_Host>
			<HostName>HostName</HostName>
		</Trigger_Host>
	</Trigger_Hosts>
</Type_0xcb>
