=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0x06.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0x06"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0x06" elementFormDefault="qualified">
	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>
	<xs:element name="Type_0x06">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				5.3.5 通用流量管理策略
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="AppType" type="u:UINT1" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="AppID" type="u:UINT2" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="AppName" type="string" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="App_Threshold_Up_ABS" type="u:UINT4"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="App_Threshold_Dn_ABS" type="u:UINT4"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="C_TimeSlots" maxOccurs="1" minOccurs="1">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="C_TimeSlot" maxOccurs="4"
										minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="C_Starttime" type="u:UINT4"
													minOccurs="1" maxOccurs="1"></xs:element>
												<xs:element name="C_Stoptime" type="u:UINT4"
													minOccurs="1" maxOccurs="1"></xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="MessageSerialNo" type="u:UINT4"
							maxOccurs="1" minOccurs="1"></xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.tester/src/main/resources/xml/msg_0x06.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type_0x06 messageNo="0" messageSequenceNo="0"
	messageSerialNo="0" xmlns="http://www.example.org/msg_0x06" xmlns:u="http://www.example.org/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/msg_0x06 ../xsd/msg_0x06.xsd ">
	<AppType>0</AppType>
	<AppID>0</AppID>
	<AppName>tns:AppName</AppName>
	<App_Threshold_Up_ABS>0</App_Threshold_Up_ABS>
	<App_Threshold_Dn_ABS>0</App_Threshold_Dn_ABS>
	<C_TimeSlots>
		<C_TimeSlot>
			<C_Starttime>0</C_Starttime>
			<C_Stoptime>0</C_Stoptime>
		</C_TimeSlot>
		<C_TimeSlot>
			<C_Starttime>0</C_Starttime>
			<C_Stoptime>0</C_Stoptime>
		</C_TimeSlot>
	</C_TimeSlots>
	<MessageSerialNo>0</MessageSerialNo>
</Type_0x06>
