=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0x45.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0x43"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0x43" elementFormDefault="qualified">

	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>

	<xs:element name="Type_0x45">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				流量流向区域对象同步策略
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="Src_AreaGroups" maxOccurs="1"
							minOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="zh">
									申请受保护的应用层攻击类型数，APP_Attack_Types子元素个数对应APP_Attack_Type_Num，1Bytes
								</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Src_AreaGroup" maxOccurs="unbounded"
										minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Src_AreaGroup_ID" type="u:UINT2"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="AS_Num" type="u:UINT1"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="AS_ID" type="u:UINT4"
													maxOccurs="1" minOccurs="1"></xs:element>
                                                                                                <xs:element name="Areas" 
													maxOccurs="256" minOccurs="1">
                                                                                                    <xs:complexType>
                                                                                                        <xs:sequence>
                                                                                                            <xs:element name="Area">
                                                                                                                <xs:complexType>
                                                                                                                    <xs:sequence>
                                                                                                                        <xs:element name="Name" type="string" maxOccurs="1" minOccurs="1"></xs:element>
                                                                                                                        
                                                                                                                    </xs:sequence>
                                                                                                                </xs:complexType>
                                                                                                            </xs:element>
                                                                                                        </xs:sequence>
                                                                                                    </xs:complexType>
                                                                                                </xs:element>      
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
                                                
                                                <xs:element name="Dest_AreaGroups" maxOccurs="1"
							minOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="zh">
									申请受保护的应用层攻击类型数，APP_Attack_Types子元素个数对应APP_Attack_Type_Num，1Bytes
								</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Dest_AreaGroup" maxOccurs="unbounded"
										minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Dest_AreaGroup_ID" type="u:UINT2"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="AS_Num" type="u:UINT1"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="AS_ID" type="u:UINT4"
													maxOccurs="1" minOccurs="1"></xs:element>
                                                                                                <xs:element name="Areas" 
													maxOccurs="256" minOccurs="1">
                                                                                                    <xs:complexType>
                                                                                                        <xs:sequence>
                                                                                                            <xs:element name="Area">
                                                                                                                <xs:complexType>
                                                                                                                    <xs:sequence>
                                                                                                                        <xs:element name="Name" type="string" maxOccurs="1" minOccurs="1"></xs:element>
                                                                                                                        
                                                                                                                    </xs:sequence>
                                                                                                                </xs:complexType>
                                                                                                            </xs:element>
                                                                                                        </xs:sequence>
                                                                                                    </xs:complexType>
                                                                                                </xs:element>      
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="MessageSerialNo" type="u:UINT4"
							maxOccurs="1" minOccurs="1" default="00000000"></xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.tester/src/main/resources/xml/流量流向/msg_0x45.xml
<?xml version="1.0" encoding="UTF-8"?>

<Type_0x45
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.ambimmort.com/msg_0x43'
    xsi:schemaLocation='http://www.ambimmort.com/msg_0x43 msg_0x45.xsd' messageNo="1" messageSerialNo="1" messageSequenceNo="1">
    <Src_AreaGroups>
        <Src_AreaGroup>
            <Src_AreaGroup_ID>1</Src_AreaGroup_ID>
            <AS_Num>1</AS_Num>
            <AS_ID>0</AS_ID>
            <Areas>
                <Area>
                    <Name>a1</Name>
                </Area>
            </Areas>
        </Src_AreaGroup>
    </Src_AreaGroups>
    <Dest_AreaGroups>
        <Dest_AreaGroup>
            <Dest_AreaGroup_ID>1</Dest_AreaGroup_ID>
            <AS_Num>1</AS_Num>
            <AS_ID>0</AS_ID>
            <Areas>
                <Area>
                    <Name>abcde</Name>
                </Area>
            </Areas>
        </Dest_AreaGroup>
    </Dest_AreaGroups>
    <MessageSerialNo>1</MessageSerialNo>

</Type_0x45>
