=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0x40.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0x40"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0x40" elementFormDefault="qualified">

	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>
	<xs:element name="Type_0x40">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				5.4.1 用户组归属分配策略
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="UserGroupNo" type="u:UINT2"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="UserGroupName" type="string"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="Action" type="u:UINT1" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="Users" maxOccurs="1" minOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="zh">
									本用户组包含的用户，Users的子元素个数对应UserNum字段，2Bytes
								</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="User" maxOccurs="999" minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="UserType" type="u:UINT1"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="UserName" type="string"
													maxOccurs="1" minOccurs="1"></xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="MessageSerialNo" type="u:UINT4"
							maxOccurs="1" minOccurs="1" default="00000000"></xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.tester/src/main/resources/xml/msg_0x40.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type_0x40 messageNo="0" messageSequenceNo="0"
	messageSerialNo="0" xmlns="http://www.example.org/msg_0x40" xmlns:u="http://www.example.org/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/msg_0x40 ../xsd/msg_0x40.xsd ">
	<UserGroupNo>0</UserGroupNo>
	<UserGroupName>UserGroupName</UserGroupName>
	<Action>0</Action>
	<Users >
		<User>
			<UserType>0</UserType>
			<UserName>UserName</UserName>
		</User>
		<User>
			<UserType>0</UserType>
			<UserName>UserName</UserName>
		</User></Users>
	<MessageSerialNo>00000000</MessageSerialNo>
</Type_0x40>
