=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0x01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0x00"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0x00" elementFormDefault="qualified">

	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>

	<xs:element name="msg_0x01">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				5.3.2 流量识别结果上报策略
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>

			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="PacketType" type="u:UINT1" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="PacketSubtype" type="u:UINT1"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="R_StartTime" type="u:UINT4"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="R_EndTime" type="u:UINT4" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="R_Freq" type="u:UINT1" maxOccurs="1"
							minOccurs="1" default="1"></xs:element>
						<xs:element name="R_DestIP" type="u:Type_IP" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="R_DestPort" type="u:UINT2" maxOccurs="1"
							minOccurs="1" default="50001"></xs:element>
						<xs:element name="R_Method" type="u:UINT1" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="UserName" type="u:FTPUserName"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="Password" type="u:FTPPassword"
							maxOccurs="1" minOccurs="1" default="user1234"></xs:element>
						<xs:element name="MessageSerialNo" type="u:UINT4"
							maxOccurs="1" minOccurs="1" default="00000000"></xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/xml/msg_0x01.xml
<?xml version="1.0" encoding="UTF-8"?>
<msg_0x01 messageNo="0" messageSequenceNo="0" messageSerialNo="0"
	xmlns="http://www.example.org/msg_0x00" xmlns:u="http://www.example.org/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/msg_0x00 msg_0x01.xsd ">
	<PacketType>0</PacketType>
	<PacketSubtype>0</PacketSubtype>
	<R_StartTime>0</R_StartTime>
	<R_EndTime>0</R_EndTime>
	<R_Freq>1</R_Freq>
	<R_DestIP>
		<u:IPType>IPv4</u:IPType>
		<u:IPv4Address>0.0.0.0</u:IPv4Address>
	</R_DestIP>
	<R_DestPort>50001</R_DestPort>
	<R_Method>0</R_Method>
	<UserName>UserName</UserName>
	<Password>user1234</Password>
	<MessageSerialNo>00000000</MessageSerialNo>
</msg_0x01>

=== hedingwei/u.uc/uc.zfserver.tester/src/main/resources/xml/流量流向/msg_0x01.xml
<?xml version="1.0" encoding="UTF-8"?>
<msg_0x01 messageNo="0" messageSequenceNo="0" messageSerialNo="0"
	xmlns="http://www.ambimmort.com/msg_0x01" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ambimmort.com/msg_0x01 msg_0x01.xsd ">
	<PacketType>1</PacketType>
	<PacketSubtype>196</PacketSubtype>
	<R_StartTime>0</R_StartTime>
	<R_EndTime>0</R_EndTime>
	<R_Freq>1</R_Freq>
	<R_DestIP>
		<u:IPType>IPv4</u:IPType>
		<u:IPv4Address>111.228.250.176</u:IPv4Address>
	</R_DestIP>
	<R_DestPort>60002</R_DestPort>
	<R_Method>1</R_Method>
	<UserName></UserName>
	<Password></Password>
	<MessageSerialNo>1</MessageSerialNo>
</msg_0x01>
