=== hedingwei/u.uc/uc.zfserver.message/src/main/resources/schemas/msg_0x42.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ambimmort.com/msg_0x42"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:u="http://www.ambimmort.com/UType"
	xmlns:tns="http://www.ambimmort.com/msg_0x42" elementFormDefault="qualified">
	<import namespace="http://www.ambimmort.com/UType" schemaLocation="UType.xsd">
	</import>

	<xs:element name="Type_0x42">
		<xs:annotation>
			<xs:documentation xml:lang="zh">
				5.4.3 一拖 N 用户管理策略
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="u:Type_UcMessage">
					<xs:sequence>
						<xs:element name="C_type" type="u:UINT1" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="C_TimeSlots" maxOccurs="1" minOccurs="1">
							<xs:annotation>
								<xs:documentation xml:lang="zh">
									管理时间段数，C_TimeSlots子元素个数对应C_TimeSlot字段，1Bytes
								</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:element name="C_TimeSlot" maxOccurs="unbounded"
										minOccurs="0">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="C_Starttime" type="u:UINT4"
													maxOccurs="1" minOccurs="1"></xs:element>
												<xs:element name="C_Stoptime" type="u:UINT4"
													maxOccurs="1" minOccurs="1"></xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="Adv_URL" type="string" maxOccurs="1"
							minOccurs="1"></xs:element>
						<xs:element name="Drop_Protocol" type="u:UINT1"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="Packet_Drop_Ratio" type="u:UINT1"
							maxOccurs="1" minOccurs="1"></xs:element>
						<xs:element name="MessageSerialNo" type="u:UINT4"
							maxOccurs="1" minOccurs="1" default="00000000"></xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</schema>

=== hedingwei/u.uc/uc.zfserver.tester/src/main/resources/xml/msg_0x42.xml
<?xml version="1.0" encoding="UTF-8"?>
<Type_0x42 messageNo="0" messageSequenceNo="0"
	messageSerialNo="0" xmlns="http://www.example.org/msg_0x42" xmlns:u="http://www.example.org/UType"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/msg_0x42 ../xsd/msg_0x42.xsd ">
	<C_type>0</C_type>
	<C_TimeSlots>
		<C_TimeSlot>
			<C_Starttime>0</C_Starttime>
			<C_Stoptime>0</C_Stoptime>
		</C_TimeSlot>
	</C_TimeSlots>
	<Adv_URL>Adv_URL</Adv_URL>
	<Drop_Protocol>0</Drop_Protocol>
	<Packet_Drop_Ratio>0</Packet_Drop_Ratio>
	<MessageSerialNo>00000000</MessageSerialNo>
</Type_0x42>
